version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: build.bat
artifacts:
- path: '**\*.nupkg'
  name: systemtime.nupkg
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master