version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: >-
    msbuild /Property:Configuration=net20 /m

    msbuild /Property:Configuration=net40 /m

    msbuild /Property:Configuration=net45 /m

    msbuild /Property:Configuration=net452 /m

    msbuild /Property:Configuration=net451 /m

    msbuild /Property:Configuration=net46 /m

    msbuild /Property:Configuration=net461 /m

    NuGet pack SystemTime/SystemTime.csproj -NonInteractive
artifacts:
- path: '**\*.nupkg'
  name: systemtime.nupkg
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master