version: 1.0.{build}
configuration:
- Net20
- Net40
- Net45
- Net451
- Net452
- Net46
- Net461
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal